env:
  browser: true
extends: 'eslint:recommended'
globals:
  Navigation: true
  Timer: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
