dist: trusty
sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
rvm:
  - 2.4.3
install:
  - bundle install --path vendor/bundle
  - npm install
before_script:
  - npm run build
script:
  - npm run test:html
  - npm run test:javascript
  - npm run test:sass
notifications:
  email: false
  slack:
    rooms:
      secure: bkE98/gnVJ1m1MFIg8WkDKl5HaRYowVbzKOjzCVHczEtEwa0rZ2To98xseP2jQafz9EtFghz3vBRY7NaL9vd8c1DgsxVrRWMfFaRhkmxmCPNhcysZ7ou4lMuutEy0JfskSgjU/3z7j7qZbnwo2xlacaUBx/c7ivAzUlGQEslvV/NQnmwr1dTSa99RIWr1Ad7d1kKXP4Fu4whNGqHL8vHJXPoX1YsSUdbe6Usf+nVRV3gTVQrL9itvJw6+GJTsgJOWmm1r5bFH94gGrxxrbidPwY6HTXpU3utSzArHcmDO+KHI51K2qdbMW4hrr8D0LdrxS/qaq7lB4drnJnWYCNHJrGOEQf+abAKOZAb7hOsQm8dpd1KgHMws+3IhsUTzJzDkEuGVKTNP9eYCAd/WDW8UxG0FZL4oAx6YAl3ZB0y/uNrHRg/u04qGu7h3PxWTG7YPL9C/j1MkCDruGXGLAw7DTnKighb4XqTjglOz6bbwcmBu36XSY+3ifqKwnopPx22adSW4OSiTrxZ1chydmukL25oUVgo/TsOiyPagl5p8Ysh1Pnn2K6uoUnb+V5JHsj8lGzxHiR5Iw4anA2XtG4HzuwnhhWdb6cbqV1hYrJ//4qyYdA+oQsxVoIYV+LyOzb2IHIrMWOljzmN6fPyZltEPjPVDGfK//Hks+FeEQEcNKI=
