[build]
publish = "public"
command = "bin/rake build"

[context.production.environment]
JEKYLL_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline';
      style-src 'self' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      frame-ancestors 'none';
      '''
    Link = '''
      <https://fonts.googleapis.com/>; rel="preconnect",
      <https://fonts.gstatic.com/>; rel="preconnect"
      '''
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
