source: ./src
destination: ./public

host: 0.0.0.0

assets:
  defaults:
    css:
      integrity: true
    img:
      integrity: false
    js:
      integrity: true
  sources:
    - _assets/javascripts
    - _assets/stylesheets
